name: api-docker-publish

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"

env:
  APP_NAME: kook
  DOCKERHUB_REPO: jerryliang/kook
  registry: ghcr.io
jobs:
  main:
    # 在 Ubuntu 上运行
    runs-on: ubuntu-latest
    steps:
      # git checkout 代码
      - name: Checkout
        uses: actions/checkout@v4
        
      # 设置 QEMU, 后面 docker buildx 依赖此.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # 设置 Docker buildx, 方便构建 Multi platform 镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
      # 构建 Docker 并推送到 Docker hub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          # 是否 docker push
          context: .
          push: true
          # 生成多平台镜像, see https://github.com/docker-library/bashbrew/blob/v0.1.1/architecture/oci-platform.go
          platforms: |
            linux/amd64
            linux/arm64/v8
          # 生成两个 docker tag: ${APP_VERSION} 和 latest
          tags: |
            ${{env.registry}}/${{env.DOCKERHUB_REPO}}:latest